<?php
// Include your database connection
require 'db.php';

echo "<div style='font-family: sans-serif; padding: 20px;'>";
echo "<h2>🚀 Generating 30 Unique Dummy Posts...</h2>";

// 1. Find an author
$user_query = $conn->query("SELECT id, username FROM users WHERE role IN ('admin', 'superadmin', 'user') LIMIT 1");

if($user_query->num_rows == 0) {
    die("<p style='color:red;'>❌ Error: No users found in the database!</p>");
}

$author = $user_query->fetch_assoc();
$author_id = $author['id'];
echo "<p>Assigning all 30 posts to author: <strong>@" . htmlspecialchars($author['username']) . "</strong></p><hr>";

// 2. Arrays to generate dynamic, realistic titles
$categories = ['Technology', 'Travel', 'Finance', 'Health', 'Sports', 'Automotive', 'Science', 'Entertainment', 'Food', 'Business'];
$prefixes = ['The Future of', '10 Tips for', 'Why Everyone is Talking About', 'A Beginner\'s Guide to', 'The Pros and Cons of', 'How to Master', 'Exploring the World of', 'The Hidden Truth About', '5 Myths About', 'The Ultimate Checklist for'];
$subjects = ['Artificial Intelligence', 'Remote Work', 'Electric Vehicles', 'Space Exploration', 'Healthy Habits', 'the Stock Market', 'Minimalism', 'Web Development', 'Photography', 'Cybersecurity', 'Smart Homes', 'Virtual Reality', 'Climate Change', 'Startup Culture'];

// 3. Dummy content
$dummy_text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. \n\nCurabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris.";

$success_count = 0;

// 4. The Loop: Generate 30 posts
for ($i = 1; $i <= 30; $i++) {
    // Generate a random title and category
    $cat = $categories[array_rand($categories)];
    $pref = $prefixes[array_rand($prefixes)];
    $subj = $subjects[array_rand($subjects)];
    
    $title = "$pref $subj";
    $content = "This is autogenerated dummy article #$i. \n\n" . $dummy_text;

    // Generate a mathematically unique image URL for every post
    $img_seed = uniqid();
    $image_path = "https://picsum.photos/seed/$img_seed/800/400";

    // Randomize the status (approx 80% published, 20% pending)
    $status = (rand(1, 10) > 8) ? 'pending' : 'published';

    // Generate a random date within the last 60 days to test sorting
    $random_days = rand(0, 60);
    $created_at = date("Y-m-d H:i:s", time() - ($random_days * 86400));

    // Escape for security
    $t = $conn->real_escape_string($title);
    $c = $conn->real_escape_string($cat);
    $cont = $conn->real_escape_string($content);
    $img = $conn->real_escape_string($image_path);
    $s = $conn->real_escape_string($status);

    $sql = "INSERT INTO posts (user_id, title, category, content, image_path, status, created_at) 
            VALUES ($author_id, '$t', '$c', '$cont', '$img', '$s', '$created_at')";
            
    if ($conn->query($sql)) {
        $success_count++;
        echo "<p style='color:#555; margin:4px 0; font-size:14px;'>✅ Added: $t</p>";
    } else {
        echo "<p style='color:red;'>❌ Error adding post: " . $conn->error . "</p>";
    }
}

echo "<hr><h3>🎉 Successfully generated $success_count massive dummy posts!</h3>";
echo "<p style='color:red; font-weight:bold;'>IMPORTANT: Delete this file (seed_massive.php) from your folder now!</p>";
echo "</div>";
?>